query($id: String!) {
  projects(where: { id: $id }) {
    id
    title
    slug
    description
    categories {
      id
      title
    }
    coverImage {
      id
      url
    }
    content {
      ... on ComponentSectionsRichText {
        content
      }
      ... on ComponentSectionsLargeMedia {
        description
      }
      ... on ComponentSectionsImagesSlider {
        title
      }
    }
  }
}
