query($id: String!) {
  projects(where: { id: $id }) {
    id
    title
    slug
    description
    categories {
      id
      title
    }
    coverImage {
      id
      url
    }
    content {
      __typename
      ... on ComponentSectionsRichText {
        id
        content
      }
    }
  }
}
